apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      serviceAccountName: developer
      containers:
      - name: restapi
        image: moficodes/restapi:v1.7.5
        ports:
        - containerPort: 7999
        resources:
          requests:
            cpu: 500m
          limits: 
            cpu: 500m
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: connection-config
              key: instance-connection-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: connection-config
              key: username
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: connection-config
              key: database
