kind: Secret
apiVersion: v1
data:
  database: BASE64_ENCODED_DB_NAME
  instance_id: BASE64_ENCODED_DB_INSTANCE_ID
  password: BASE64_ENCODED_DB_PASSWORD
  username: BASE64_ENCODED_DB_USER
metadata:
  name: connection-config